version: '2'

services: 
  
  traccar:
    image: traccar/traccar 
    restart: always
    env_file: .env
    expose:
      - "5000-5150"
      - "5000-5150/udp"
      - "8082"
    volumes:
      - ./.traccar:/opt/traccar/data/database
      - ./conf/traccar.xml:/opt/traccar/conf/traccar.xml
      - ./conf/release.html:/opt/traccar/web/release.html
      - ./conf/index.html:/opt/traccar/web/simple/index.html
      - /var/docker/traccar/logs:/opt/traccar/logs:rw 
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro 

  server:
    image: abiosoft/caddy 
    depends_on:
      - traccar
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/Caddyfile
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME} 

volumes:
  traccar: {}

